// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwNInzG2yES0uwgqEAMlizS0NYfwuoX6Y',
    appId: '1:704090168051:web:6772314d40536ae47e7586',
    messagingSenderId: '704090168051',
    projectId: 'flutterapp-kp',
    authDomain: 'flutterapp-kp.firebaseapp.com',
    storageBucket: 'flutterapp-kp.appspot.com',
    measurementId: 'G-BGNB8C54NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9eqUyepGsHw8T3Yfpk3SUGqBDixizBo',
    appId: '1:704090168051:android:09619a2f3296bcc27e7586',
    messagingSenderId: '704090168051',
    projectId: 'flutterapp-kp',
    storageBucket: 'flutterapp-kp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAe-uV8imlZ5HU0Ps2qfjXn_AKPu_DupA',
    appId: '1:704090168051:ios:4463d5639abe91057e7586',
    messagingSenderId: '704090168051',
    projectId: 'flutterapp-kp',
    storageBucket: 'flutterapp-kp.appspot.com',
    iosBundleId: 'com.example.flutterfirekp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAe-uV8imlZ5HU0Ps2qfjXn_AKPu_DupA',
    appId: '1:704090168051:ios:b13b49d8856a94e87e7586',
    messagingSenderId: '704090168051',
    projectId: 'flutterapp-kp',
    storageBucket: 'flutterapp-kp.appspot.com',
    iosBundleId: 'com.example.flutterfirekp.RunnerTests',
  );
}
